### ISSUE TITLE
Wrong number of available parkings

### ISSUE THREAD

**Issue by hbruch** [stadtnavi/stadtnavi_app#287]
**Describe the bug**
The app shows wrong number of available parkings.

**To Reproduce**
1. Go to e.g. parking `Unter Graben Graben`
2. Open details
3. See e.g. `142 von 39 Stellplätzen verfügbar`

**Expected behavior**
Number of parkings should be the same as displayed in herrenberg.stadtnavi.de / https://api.stadtnavi.de/herrenberg/parking/parkapi.json

**Screenshots**
Wrong number in App:
![grafik](https://user-images.githubusercontent.com/2187389/148251600-755e9a7f-69a4-4e73-931c-ba83c32e7382.png)

 Correct Number in ParkAPI:
<img width="1073" alt="grafik" src="https://user-images.githubusercontent.com/2187389/148252327-5723375d-7ae4-4558-ae87-286256ba0148.png">

Correct Number in webapp:
<img width="487" alt="grafik" src="https://user-images.githubusercontent.com/2187389/148252414-90170cd3-7d6c-44c0-8582-d83022e4e244.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12mini
 - OS: 15.1.1
- OS: stadtnavi App iOS
 - Version: Where can is see the app version?

**Additional context**

**Comment by SamuelRioTz** [comment]
@hbruch so I did the review and here is the results:
On the app mobile app we were using `https://api.dev.stadtnavi.eu` with `/routing/v1/router/vectorTiles/parking/$z/$x/$y.pbf` tiles.
and in the web site is using different server: `https://api.stadtnavi.de` with `/routing/v1/router/vectorTiles/parking/$z/$x/$y.pbf` tiles.
So we were using the **DEV env**.
So I think changing the **dev** url to **prod** url should fix that issues.

**Comment by SamuelRioTz** [comment]
about caching I was wrong, we are not using cache memory for parkings data, we are just using memory ram persistence, and each parking information is loaded when you zoom in/out or moving the map.
since there is no way to load a single parking information for example using the parking ID, so is not possible to refetch whithout reloading the whole map with whole information which is really hard for mobile phone.
So id could be possible to use this `https://api.stadtnavi.de/herrenberg/parking/parkapi.json`? it seems not too heavy or there is another endoint for fetch a single parking information? so we can fetch everytime when open the pop-up and also we can put a timer there for fetch the data every some time

**Comment by hbruch** [comment]
@SamuelRioTz no external data source should be used than the stadtnavi service, as further parkApi sources can and wil be added. 

Besides showing outdated occupancy numbers, we get feedback that static parkings are showing availability numbers, which should not be the case. Did you change from dev to prod system? This should be addressed rather soon. 

In case you would not reload the vector tiles, you might consider using a graphql query against `https://api.stadtnavi.de/routing/v1/router/index/graphql`, e.g. `{ vehicleParkings {id name  openingHours note capacity a{ carSpaces bicycleSpaces wheelchairAccessibleCarSpaces} availability { carSpaces bicycleSpaces wheelchairAccessibleCarSpaces} lat lon}} `

**Comment by hbruch** [comment]
@SamuelRioTz @Denis306 Did you have a look into this issue?

**Comment by SamuelRioTz** [comment]
@hbruch already fixed, it will be present on the next release
