### ISSUE TITLE
Enhance Map Layers by missing ones

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#31]

**Comment by md-weber** [comment]
Please add a description @Denis306

**Comment by SamuelRioTz** [comment]
@md-weber 
some maps layers comes from _.pbf_ map tiles, the challenges is add these layers
![Screen Shot 2021-05-09 at 17 44 15](https://user-images.githubusercontent.com/43000324/117587932-6f3e7000-b0ee-11eb-91ab-03fc1814fa21.png)

**Comment by leonardehrenfried** [comment]
So the GeoJson layers contain "small" datasets like all the bike shops in the district. There are at most a few hundred items in there. This data is updated manually every few months.

The other layers cotain potentially several thousands of points distributed all over Baden-Württemberg. On top of this the data (particularly bus stops) change every so often. For this reason we use a so-called vector tile server. 

It works by the client requesting a small square of data and the tile server returning just the data in this square. This means you don't have to preload the list of several thousand bus stops in the client.

The technology is called Mapbox Vector Tiles. I think when googling this, you will find information about how it works. Otherwise you can also ask me.
