### ISSUE TITLE
Show Push Notification in the App when you click on it

### ISSUE THREAD

**Issue by Denis306** [stadtnavi/stadtnavi_app#358]
Currently stadtnavi Herrenberg already has implemented Push Notifications. However, these disappear when you click on them and the user can't potentially read the whole message. For that, the notifications need to open the app and be displayed in a window within the application.

- [x] Implement / Prepare Container frame and screenshot for the push notification
- [x] Implement configuration to open application after clicking on the notification
- [x] Integrate the data of the push notifications with the container within the app so users can read the full message
- [x] Add an "x" button at the top right corner to close the notification once opened in the app.
- [x] Make the title break into as many lines as possible. (Infinite breaks)

**Comment by Denis306** [comment]
Hi @stadtnavimanager,
this is what the screen would look like when opening a push notification:
![image](https://github.com/user-attachments/assets/68fa214c-a7d1-4852-90db-883eb4e53656)

If it is okay for you, we would continue with the work on the other open topics.

**Comment by stadtnavimanager** [comment]
Hi @Denis306 ,
some questions:

1. what happens if the user clicks on "Nicht mehr anzeigen" vs. "OK"?
2. this window is only connected to the push-notification, not the in-app notification, right? so it won't be possible to have links to an external page in this window?
3. will the format adapt to the text? e.g. if the headline is longer than one line, will it be shown in two lines? 
4. if the text is longer than that window, will there be an option "show more" and the possibility to scroll throught the entire text?

Thank you

**Comment by GustavoTCh** [comment]
@stadtnavimanager

1.	What happens if the user clicks on “Nicht mehr anzeigen” vs. “OK”?
	•	**When the user clicks on “Nicht mehr anzeigen” (Do not show again), the specific notification will not be shown again in the future. If the user clicks “OK,” it simply closes the notification without affecting future notifications.**
2.	Is this window only connected to the push notification, not the in-app notification? Is it possible to include links to an external page in this window?
	•	**Yes, this window is connected to the push notification. However, we can configure the home screen to also accept in-app notifications. Additionally, push notifications can include buttons that link to external pages.**
3.	Will the format adapt to the text? For example, if the headline is longer than one line, will it be shown in two lines?
	•	**Yes, the format will adapt to the text. If the headline is longer than one line, it will automatically wrap and be displayed on two lines.**
4.	If the text is longer than the window, will there be an option to “show more” and the possibility to scroll through the entire text?
	•	**Yes, we can enable a “show more” option, or we can implement scrolling within the popup if the text exceeds the available space.**

**Comment by stadtnavimanager** [comment]
@GustavoTCh 
thanks for your reply!
1. ok
2. regarding the push-notification & link: sounds good. regarding the in-app notification: would there be an advantage if we also connect it to the in-app notifications, from your perspective? @Denis306 maybe we can talk about this on monday
3. great
4. ok. probably a show more button + scrolling is necessary, right? because if you click "show more" and then the entire text shows, the user must be able to scroll. maybe you can describe the solution you think is best?

**Comment by GustavoTCh** [comment]
it’s possible to create an in-app notification triggered by common events like on_foreground and app_launch, with a frequency of once per day. Additionally, we can use push notifications to send daily reminders, incorporating custom buttons through additional parameters

**Comment by GustavoTCh** [comment]
Report and improves:

1. Notification Configuration: We have successfully implemented the configuration for in-app notifications and resolved previous issues with push notifications.
2. Enhanced Push Notification Handling (Pending):
	•	Opening the App with Notification Content: We plan to improve functionality so that when a push notification is clicked, the app opens directly to display the notification content.
	•	Actionable Push Notifications: Since the Flutter Firebase plugin does not natively support actions in push notifications, we plan to implement a custom popup solution that will allow users to interact with notifications through actions.
3. Support for Long Text in Notifications (Pending):
	•	The next image illustrates our implementation for handling long text in in-app notifications. We plan to use a similar styling approach to support long text in our custom popup push notifications.

![WhatsApp Image 2024-08-19 at 04 22 47](https://github.com/user-attachments/assets/a8fe02e2-9cfd-48fe-bcfc-b9cc87aa111a)

**Comment by GustavoTCh** [comment]
@stadtnavimanager 
I’ve made improvements and resolved bugs related to push notifications in version 1.9.2:

1. When you open a notification, the app now launches and displays a popup containing the notification details.
![WhatsApp Image 2024-08-22 at 04 26 10](https://github.com/user-attachments/assets/ebdf984a-6b2d-45d4-8150-7856b17c52b1)

2. The popup includes a title, description, image, and configurable actions. The actions can be set through additional parameters in the Firebase console, where you can define 1 or 2 buttons. The key is textButton, and the value can be a URL. If the value is not a URL, the button will close the popup instead. I’ll provide more details once I have the documentation ready. 
![WhatsApp Image 2024-08-22 at 04 26 10 (1)](https://github.com/user-attachments/assets/7d8f8975-6ea8-4fe2-b04a-998887b532b0)

3. I’ve configured daily push notifications to be sent at 11 AM in Germany with the message: “New Route Available! 🚗✨ Every day at 11 AM.”

**Comment by Denis306** [comment]
Done.
